name: ticketspartyapp
description: Tickets Party Mobile App


version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^1.0.3
  meta: ^1.1.8
  flutter_svg: ^0.17.4
  qr_code_scanner: ^0.0.13
  flutter_launcher_icons: ^0.7.5
  equatable: ^1.2.0
  carousel_slider: ^2.1.0
  http: ^0.12.1
  cupertino_icons: ^0.1.3
  flutter_secure_storage: ^3.3.3
  flutter_bloc: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "resources/logo.png"

flutter:
  assets:
    - resources/
  uses-material-design: true

