name: ticketspartyapp
description: Tickets Party Mobile App


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^1.0.3
  meta: ^1.1.8
  equatable: ^1.1.1
  http: ^0.12.1
  cupertino_icons: ^0.1.3
  flutter_secure_storage: ^3.3.3
  flutter_bloc: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

